2023-09-17 08:03:40,252 - speechbrain.core - INFO - Beginning experiment!
2023-09-17 08:03:40,253 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-17 08:03:40,716 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-17 08:03:40,726 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-17 08:03:40,795 - librispeech_prepare - INFO - Data_preparation...
2023-09-17 08:03:40,795 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 363, in <module>
    run_on_main(
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/librispeech_prepare.py", line 111, in prepare_librispeech
    check_librispeech_folders(data_folder, splits)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/librispeech_prepare.py", line 456, in check_librispeech_folders
    raise OSError(err_msg)
OSError: the folder LibriSpeech/train-clean-100 does not exist (it is expected in the Librispeech dataset)
2023-09-17 17:16:00,936 - speechbrain.core - INFO - Beginning experiment!
2023-09-17 17:16:00,937 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-17 17:16:05,839 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-17 17:16:05,848 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-17 17:16:05,974 - librispeech_prepare - INFO - Data_preparation...
2023-09-17 17:16:26,676 - librispeech_prepare - INFO - Creating csv lists in  results/train_wav2vec2_libri_100/3407/train-clean-100.csv...
2023-09-17 17:20:12,186 - librispeech_prepare - INFO - results/train_wav2vec2_libri_100/3407/train-clean-100.csv successfully created!
2023-09-17 17:21:44,286 - librispeech_prepare - INFO - Creating csv lists in  results/train_wav2vec2_libri_100/3407/train-clean-360.csv...
2023-09-17 17:24:54,001 - librispeech_prepare - INFO - results/train_wav2vec2_libri_100/3407/train-clean-360.csv successfully created!
2023-09-17 17:27:19,947 - librispeech_prepare - INFO - Creating csv lists in  results/train_wav2vec2_libri_100/3407/train-other-500.csv...
2023-09-17 17:30:40,945 - librispeech_prepare - INFO - results/train_wav2vec2_libri_100/3407/train-other-500.csv successfully created!
2023-09-17 17:30:42,847 - librispeech_prepare - INFO - Creating csv lists in  results/train_wav2vec2_libri_100/3407/dev-clean.csv...
2023-09-17 17:31:42,746 - librispeech_prepare - INFO - results/train_wav2vec2_libri_100/3407/dev-clean.csv successfully created!
2023-09-17 17:31:44,071 - librispeech_prepare - INFO - Creating csv lists in  results/train_wav2vec2_libri_100/3407/test-clean.csv...
2023-09-17 17:32:34,588 - librispeech_prepare - INFO - results/train_wav2vec2_libri_100/3407/test-clean.csv successfully created!
2023-09-17 17:32:37,055 - librispeech_prepare - INFO - Creating csv lists in  results/train_wav2vec2_libri_100/3407/test-other.csv...
2023-09-17 17:33:29,754 - librispeech_prepare - INFO - results/train_wav2vec2_libri_100/3407/test-other.csv successfully created!
2023-09-17 17:33:30,361 - speechbrain.dataio.dataio - INFO - results/train_wav2vec2_libri_100/3407/train.csv is created.
2023-09-17 17:33:32,699 - speechbrain.dataio.encoder - DEBUG - Would load categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt, but file doesn't exist yet.
2023-09-17 17:33:37,961 - speechbrain.dataio.encoder - INFO - Moving label 'I' from index 0, because '<blank>' was put at its place.
2023-09-17 17:33:37,964 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-17 17:33:37,965 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-17 17:33:37,965 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-17 17:33:37,965 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-17 17:33:46,721 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-17 17:33:46,721 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-17 17:33:46,723 - speechbrain.pretrained.fetching - INFO - Fetch latent_extractor.ckpt: Delegating to Huggingface hub, source facebook/wav2vec2-base-960h.
2023-09-17 17:33:47,365 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2023-09-17 17:33:47,666 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt HTTP/1.1" 404 0
2023-09-17 17:33:47,689 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1606, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-650770bb-283f479159c223a23ae7a9c0;5c70a41c-7b80-4f14-8801-1aac23a83280)

Entry Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 416, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
           ^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 171, in fetch
    raise ValueError("File not found on HF hub")
ValueError: File not found on HF hub
2023-09-17 17:35:02,679 - speechbrain.core - INFO - Beginning experiment!
2023-09-17 17:35:02,680 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-17 17:35:06,734 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-17 17:35:06,741 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-17 17:35:06,895 - librispeech_prepare - INFO - Skipping preparation, completed in previous run.
2023-09-17 17:35:09,193 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-17 17:35:09,193 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-17 17:35:09,193 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-17 17:35:09,194 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-17 17:35:09,194 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-17 17:35:11,152 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-17 17:35:11,152 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-17 17:35:11,153 - speechbrain.pretrained.fetching - INFO - Fetch latent_extractor.ckpt: Delegating to Huggingface hub, source facebook/wav2vec2-base-960h.
2023-09-17 17:35:11,190 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2023-09-17 17:35:11,355 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt HTTP/1.1" 404 0
2023-09-17 17:35:11,357 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1606, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-6507710f-796ed23826322fc23beef488;b6e54a84-93b6-42b9-976a-87e23eeb4ef4)

Entry Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 416, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
           ^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 171, in fetch
    raise ValueError("File not found on HF hub")
ValueError: File not found on HF hub
2023-09-17 17:39:26,240 - speechbrain.core - INFO - Beginning experiment!
2023-09-17 17:39:26,242 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-17 17:39:26,694 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-17 17:39:26,698 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-17 17:39:26,823 - librispeech_prepare - INFO - Skipping preparation, completed in previous run.
2023-09-17 17:39:29,106 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-17 17:39:29,106 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-17 17:39:29,106 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-17 17:39:29,106 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-17 17:39:29,106 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-17 17:39:31,144 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-17 17:39:31,144 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-17 17:39:31,145 - speechbrain.pretrained.fetching - INFO - Fetch latent_extractor.ckpt: Delegating to Huggingface hub, source facebook/wav2vec2-base-960h.
2023-09-17 17:39:31,177 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2023-09-17 17:39:31,348 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt HTTP/1.1" 404 0
2023-09-17 17:39:31,349 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1606, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-65077213-0d5fdc4626feac1e3812ba19;0c647ffb-791b-4b49-9bc2-0af9c9baec59)

Entry Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 416, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
           ^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 171, in fetch
    raise ValueError("File not found on HF hub")
ValueError: File not found on HF hub
2023-09-17 17:40:40,825 - speechbrain.core - INFO - Beginning experiment!
2023-09-17 17:40:40,826 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-17 17:40:41,332 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-17 17:40:41,342 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-17 17:40:41,463 - librispeech_prepare - INFO - Skipping preparation, completed in previous run.
2023-09-17 17:40:44,038 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-17 17:40:44,039 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-17 17:40:44,039 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-17 17:40:44,039 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-17 17:40:44,039 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-17 17:40:46,120 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-17 17:40:46,121 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-17 17:40:46,122 - speechbrain.pretrained.fetching - INFO - Fetch latent_extractor.ckpt: Delegating to Huggingface hub, source facebook/wav2vec2-base-960h.
2023-09-17 17:40:46,157 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2023-09-17 17:40:46,347 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt HTTP/1.1" 404 0
2023-09-17 17:40:46,348 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1606, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-6507725e-642bd4a3652bad025b21f124;c7ce514a-aad6-42af-b78a-6b8a1abff542)

Entry Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 416, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
           ^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 171, in fetch
    raise ValueError("File not found on HF hub")
ValueError: File not found on HF hub
2023-09-18 09:17:48,858 - speechbrain.core - INFO - Beginning experiment!
2023-09-18 09:17:48,877 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-18 09:17:52,220 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-18 09:17:52,228 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-18 09:17:52,319 - librispeech_prepare - INFO - Skipping preparation, completed in previous run.
2023-09-18 09:17:54,889 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:17:54,889 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-18 09:17:54,890 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:17:54,890 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-18 09:17:54,890 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-18 09:17:59,702 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-18 09:17:59,703 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-18 09:17:59,703 - speechbrain.pretrained.fetching - INFO - Fetch latent_extractor.ckpt: Delegating to Huggingface hub, source facebook/wav2vec2-base-960h.
2023-09-18 09:17:59,921 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2023-09-18 09:18:00,100 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt HTTP/1.1" 404 0
2023-09-18 09:18:00,109 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1606, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-65084e08-52d5bd251d4f268036800f31;f6631d84-19c4-4b72-9b15-440eb7b9e6dd)

Entry Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 416, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
           ^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 171, in fetch
    raise ValueError("File not found on HF hub")
ValueError: File not found on HF hub
2023-09-18 09:19:01,102 - speechbrain.core - INFO - Beginning experiment!
2023-09-18 09:19:01,103 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-18 09:19:01,673 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-18 09:19:01,677 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-18 09:19:01,741 - librispeech_prepare - INFO - Skipping preparation, completed in previous run.
2023-09-18 09:19:04,121 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:19:04,122 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-18 09:19:04,122 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:19:04,122 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-18 09:19:04,122 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-18 09:19:06,252 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-18 09:19:06,253 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-18 09:19:06,253 - speechbrain.pretrained.fetching - INFO - Fetch latent_extractor.ckpt: Delegating to Huggingface hub, source facebook/wav2vec2-base-960h.
2023-09-18 09:19:06,291 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2023-09-18 09:19:06,464 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt HTTP/1.1" 404 0
2023-09-18 09:19:06,466 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1606, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-65084e4a-6a04f5100cbe95674b3cfcfe;4f858301-5d6c-4f7f-ab73-e2ded5ed69f9)

Entry Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 416, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
           ^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 171, in fetch
    raise ValueError("File not found on HF hub")
ValueError: File not found on HF hub
2023-09-18 09:19:44,176 - speechbrain.core - INFO - Beginning experiment!
2023-09-18 09:19:44,177 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-18 09:19:44,604 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-18 09:19:44,607 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-18 09:19:44,662 - librispeech_prepare - INFO - Skipping preparation, completed in previous run.
2023-09-18 09:19:47,303 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:19:47,303 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-18 09:19:47,304 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:19:47,304 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-18 09:19:47,304 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-18 09:19:49,076 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-18 09:19:49,077 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-18 09:19:49,078 - speechbrain.pretrained.fetching - INFO - Fetch latent_extractor.ckpt: Delegating to Huggingface hub, source facebook/wav2vec2-base-960h.
2023-09-18 09:19:49,105 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2023-09-18 09:19:49,311 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt HTTP/1.1" 404 0
2023-09-18 09:19:49,313 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1606, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-65084e75-0ab7c9640a097f603278e387;684259b1-0282-4841-91b3-9d9cf518004d)

Entry Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 416, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
           ^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 171, in fetch
    raise ValueError("File not found on HF hub")
ValueError: File not found on HF hub
2023-09-18 09:22:55,836 - speechbrain.core - INFO - Beginning experiment!
2023-09-18 09:22:55,838 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-18 09:22:56,413 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-18 09:22:56,417 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-18 09:22:56,480 - librispeech_prepare - INFO - Skipping preparation, completed in previous run.
2023-09-18 09:22:58,979 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:22:58,979 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-18 09:22:58,979 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:22:58,979 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-18 09:22:58,980 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-18 09:23:01,121 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-18 09:23:01,122 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-18 09:23:01,122 - speechbrain.pretrained.fetching - INFO - Fetch latent_extractor.ckpt: Delegating to Huggingface hub, source facebook/wav2vec2-base-960h.
2023-09-18 09:23:01,153 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2023-09-18 09:23:01,285 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt HTTP/1.1" 404 0
2023-09-18 09:23:01,286 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1606, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-65084f35-35cf93f952d4204361ef435c;f24705d4-a844-4982-8c8a-236a917c805a)

Entry Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 417, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
           ^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 171, in fetch
    raise ValueError("File not found on HF hub")
ValueError: File not found on HF hub
2023-09-18 09:29:41,937 - speechbrain.core - INFO - Beginning experiment!
2023-09-18 09:29:41,938 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-18 09:29:42,383 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-18 09:29:42,387 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-18 09:29:42,447 - librispeech_prepare - INFO - Skipping preparation, completed in previous run.
2023-09-18 09:29:44,984 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:29:44,984 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-18 09:29:44,985 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:29:44,985 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-18 09:29:44,993 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-18 09:29:47,088 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-18 09:29:47,088 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-18 09:29:47,089 - speechbrain.pretrained.fetching - INFO - Fetch latent_extractor.ckpt: Delegating to Huggingface hub, source facebook/wav2vec2-base-960h.
2023-09-18 09:29:47,118 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2023-09-18 09:29:47,257 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt HTTP/1.1" 404 0
2023-09-18 09:29:47,258 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 161, in fetch
    fetched_file = huggingface_hub.hf_hub_download(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1230, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1606, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-650850cb-7b21796b493523c83964648e;237539db-b934-4310-839c-4f1dc1a1b022)

Entry Not Found for url: https://huggingface.co/facebook/wav2vec2-base-960h/resolve/main/latent_extractor.ckpt.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 416, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/distributed.py", line 61, in run_on_main
    func(*args, **kwargs)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 247, in collect_files
    path = fetch(
           ^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/pretrained/fetching.py", line 171, in fetch
    raise ValueError("File not found on HF hub")
ValueError: File not found on HF hub
2023-09-18 09:59:04,775 - speechbrain.core - INFO - Beginning experiment!
2023-09-18 09:59:04,776 - speechbrain.core - INFO - Experiment folder: results/train_wav2vec2_libri_100/3407
2023-09-18 09:59:05,428 - speechbrain.utils.superpowers - DEBUG - attrs==23.1.0
certifi==2023.7.22
charset-normalizer==3.2.0
cmake==3.27.4.1
contourpy==1.1.1
cycler==0.11.0
filelock==3.12.4
fonttools==4.42.1
fsspec==2023.9.1
huggingface-hub==0.17.1
HyperPyYAML==1.2.1
hypothesis==6.86.1
idna==3.4
Jinja2==3.1.2
joblib==1.3.2
kenlm==0.2.0
kiwisolver==1.4.5
lit==16.0.6
MarkupSafe==2.1.3
matplotlib==3.8.0
mpmath==1.3.0
networkx==3.1
numpy==1.26.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.1.0
Pillow==10.0.1
pyctcdecode==0.5.0
pygtrie==2.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
ruamel.yaml==0.17.28
ruamel.yaml.clib==0.2.7
safetensors==0.3.3
scipy==1.11.2
sentencepiece==0.1.99
six==1.16.0
sortedcontainers==2.4.0
speechbrain==0.5.15
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
tqdm==4.66.1
transformers==4.33.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4


2023-09-18 09:59:05,435 - speechbrain.utils.superpowers - DEBUG - 6c7e9b6


2023-09-18 09:59:05,499 - librispeech_prepare - INFO - Skipping preparation, completed in previous run.
2023-09-18 09:59:08,198 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:59:08,198 - speechbrain.dataio.encoder - INFO - Load called, but CTCTextEncoder is not empty. Loaded data will overwrite everything. This is normal if there is e.g. an unk label defined at init.
2023-09-18 09:59:08,198 - speechbrain.dataio.encoder - DEBUG - Loaded categorical encoding from results/train_wav2vec2_libri_100/3407/save/label_encoder.txt
2023-09-18 09:59:08,198 - speechbrain.core - INFO - Info: auto_mix_prec arg from hparam file is used
2023-09-18 09:59:08,199 - speechbrain.core - INFO - Info: ckpt_interval_minutes arg from hparam file is used
2023-09-18 09:59:09,906 - speechbrain.core - INFO - 94.5M trainable parameters in ASR
2023-09-18 09:59:09,907 - speechbrain.utils.parameter_transfer - DEBUG - Collecting files (or symlinks) for pretraining in results/train_wav2vec2_libri_100/3407/save.
2023-09-18 09:59:09,910 - speechbrain.pretrained.fetching - INFO - Destination latent_extractor.ckpt: local file in /gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/model_checkpoints/models--facebook--wav2vec2-large-960h-lv60-self/latent_extractor.ckpt.
2023-09-18 09:59:09,910 - speechbrain.pretrained.fetching - INFO - Destination latent_encoder.ckpt: local file in /gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/model_checkpoints/models--facebook--wav2vec2-large-960h-lv60-self/latent_encoder.ckpt.
2023-09-18 09:59:09,910 - speechbrain.utils.parameter_transfer - INFO - Loading pretrained files for: extractor, encoder_wrapper
2023-09-18 09:59:09,910 - speechbrain.utils.parameter_transfer - INFO - Redirecting (loading from original path): results/train_wav2vec2_libri_100/3407/save/extractor.ckpt -> /gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/model_checkpoints/models--facebook--wav2vec2-large-960h-lv60-self/latent_extractor.ckpt
2023-09-18 09:59:09,910 - speechbrain.utils.parameter_transfer - INFO - Redirecting (loading from original path): results/train_wav2vec2_libri_100/3407/save/encoder_wrapper.ckpt -> /gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/model_checkpoints/models--facebook--wav2vec2-large-960h-lv60-self/latent_encoder.ckpt
2023-09-18 09:59:09,911 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/train_with_wave2vec.py", line 417, in <module>
    hparams["pretrainer"].load_collected(asr_brain.device)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 320, in load_collected
    self._call_load_hooks(paramfiles, device)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/parameter_transfer.py", line 337, in _call_load_hooks
    default_hook(obj, loadpath, device=device)
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/speechbrain/utils/checkpoints.py", line 145, in torch_parameter_transfer
    torch.load(path, map_location=device), strict=False
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/venv/lib/python3.11/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/u/scratch/NLUG/NLUGcbsm/phonetic-error-corrector/model_checkpoints/models--facebook--wav2vec2-large-960h-lv60-self/latent_extractor.ckpt'
